image: Ubuntu2004
build: off
install:
- sudo bash bats.sh
- sudo bash skaffold.sh
- sudo bash minikube.sh
- sudo minikube start --force --driver=docker
- sudo skaffold config set --global collect-metrics true
- git clone --depth 1 https://github.com/GoogleContainerTools/skaffold
test_script:
- sh: |
    cd $APPVEYOR_BUILD_FOLDER/skaffold/examples/getting-started/
    cat <<'__eot__' >main.go
    package main

    import (
            "fmt"
            "time"
    )

    func main() {
    	for i := 0; i < 10; i++ {
                    fmt.Println("Hello world!")
                    time.Sleep(time.Second * 1)
            }
    }
    __eot__

    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    git commit -am 'stuff and things'
    pwd
    sudo bash -c 'pwd && skaffold dev'
